### ISSUE TITLE
BBS+ test case is failing

### ISSUE THREAD

**Issue by fqutishat** [w3c-ccg/vc-http-api#133]
test case 16 is passing https://github.com/w3c-ccg/vc-http-api/blob/master/packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/case-16.json

test case 17 is failing (bad signature) https://github.com/w3c-ccg/vc-http-api/blob/master/packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/case-17.json 

what is the difference between case 16 and 17

same pattern for 18 (passing) && 19 (bad signature)

**Comment by fqutishat** [comment]
@tplooker

**Comment by troyronda** [comment]
@fqutishat
Case 16: BbsBlsSignature2020
Case 17: BbsBlsSignatureProof2020
