### ISSUE TITLE
case 7 is failing due to schema.org context drift

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-http-api#148]
https://github.com/w3c-ccg/vc-http-api/blob/master/packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/case-7.json#L4

I can't get this to pass, even if I pull down 100% of schema.org from https://schema.org/version/latest/schemaorg-current-https.jsonld

I suspect this is due to context drift....

see https://schema.org/docs/releases.html

this is why in the traceability vocab, we only pull terms we use.

and control our context via CI/CD

It also highlights that we need to upgrade to https IRIs ASAP.

**Comment by OR13** [comment]
its probably good to have a couple negative tests... we should just make sure we intend for them to fail.

**Comment by OR13** [comment]
Really we ought to keep these baddies around somewhere, with some explanation of why they are bad...

**Comment by peacekeeper** [comment]
Hmm that case 7 is passing for me, but I guess I'm using an older version of the schema.org context (attaching it here, changed file extension from .jsonld to .txt):

[schema-org.txt](https://github.com/w3c-ccg/vc-http-api/files/6105934/schema-org.txt)

**Comment by mkhraisha** [comment]
I think this is a pretty old test schema. the newer ones from the traceability vocab arent in there

**Comment by peacekeeper** [comment]
I think this has been fixed by https://github.com/w3c-ccg/vc-http-api/pull/158 and can be closed?

**Comment by OR13** [comment]
agreed.
