### ISSUE TITLE
Vendor test results leaking across reports

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-http-api#153]
<img width="1513" alt="Screen Shot 2021-03-08 at 8 04 22 PM" src="https://user-images.githubusercontent.com/8295856/110407495-878c0300-8049-11eb-88b1-c913dc60b122.png">

**Comment by mkhraisha** [comment]
Is this still a thing @OR13 ?

**Comment by OR13** [comment]
Maybe not after timeouts got bumped. I am going to close for now.
