### ISSUE TITLE
Rename 'master' to 'main'

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/vc-http-api#171]
I just renamed the 'master' branch to 'main' and updated all the things (retargeted branches, set main branch, deleted master, etc.). I'm opening an issue in case anyone wants to object. I doubt anyone would, but just putting that out there.

This issue will be closed in 7 days if there are no objections.

**Comment by msporny** [comment]
@OR13 I noticed that we're serving web content from gh-pages -- why? I expect there is some build process that I'm not aware of doing this?

**Comment by bumblefudge** [comment]
Not sure if this is pertinent but `jekyll` and various other github-based JS sitebuilders I've used (docusaurus, minimal mistakes, DIF's home-brew one) all default to `gh-pages/docs/` as the home directory of websites. AFAIK this is and has long been the "default" configuration when you turn on github.io hosting for a repo for the first time on github.com.  À propos of this thread, though, I'm noticing that w3c-ccg.github.io doesn't do it this way... would love pointers if there's context here that I'm missing.

**Comment by bumblefudge** [comment]
Also, whatever/however we're building this site, there seems to be an index.html missing from 
https://w3c-ccg.github.io/vc-http-api/test-suite/
and 
https://w3c-ccg.github.io/vc-http-api/

although
https://w3c-ccg.github.io/vc-http-api/test-suite/<vendor>/
is working fine.  This site is exactly what I wanted to discuss on Wednesday! Happy to help any way I can.

**Comment by msporny** [comment]
> I'm noticing that w3c-ccg.github.io doesn't do it this way... would love pointers if there's context (i.e. best-practices) that I'm missing.

I set that up -- it doesn't do it that way because the main branch *is* the website, so doesn't make sense to put it on gh-pages. I tend to be a fairly strong -1 on anything that has "the website" on a totally different, completely irreconcilable branch from the main branch. There are few benefits to that approach other than gh-pages being a dumping ground for auto-generated content.

**Comment by OR13** [comment]
IMO serving a website out of the main / master branch is terrible for anything other than a spec.

- PRs should not include built assets
- CI should handle lint, test, build and deploy
- merges to main / master should be blocked in CI fails.
- direct push to main / master should be impossible.

When your CI pipeline builds and tests your software and you want to automatically publish reports, you can do 1 of 2 things...
1. Have your CI merge latest test results into main / master (boooo / yuk).
2. Have your CI push latest test results when it does github pages deploy (yay clean!).

Your git history on main will get filled with "deployed c82eb...." commits if you do 1 AND you will constantly be fighting merge conflicts for dist assets....


If you do 2, CI will automatically deploy the latest main and all test results for every merge to main, and all programmatically generated stuff can be safely git ignored.

**Comment by peacekeeper** [comment]
No strong opinion here on whether to serve content from main or gh-pages (Orie's explanation makes sense to me), but in any case big +1 to renaming master to main :)

**Comment by msporny** [comment]
`master` was renamed to `main` a while ago... we still serve things out of gh-pages. Closing.
