### ISSUE TITLE
VC HTTP API specification structure

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/vc-http-api#182]
The VC HTTP API Task Force has attempted to take up the following proposals on the last two calls:

PROPOSAL: Create 1 ReSpec specification in addition to separating the existing OAS files into modular components.
PROPOSAL: Create 3 VC HTTP API ReSpec specifications (e.g., Issuing, Verification, Presentation) in addition to the existing OAS file.

The first proposal has a lot of support, the second proposal has a large number of detractors. The full thread can be read here:

https://lists.w3.org/Archives/Public/public-credentials/2021Apr/0196.html

The fundamental question is "What sort of structure should the VC HTTP API Specification take?"

**Comment by peacekeeper** [comment]
I think proposal 1 makes the most sense. One challenge with proposal 2 is that there may be shared content that cannot be clearly associated with only a single one of the three specifications, so it wouldn't be obvious where it belongs, or such shared content would have to be duplicated (= not good).

**Comment by msporny** [comment]
This was resolved during one of the calls:

RESOLUTION: Create 1 ReSpec specification based on the OAS files, in addition to separating the existing OAS files into modular components.

https://w3c-ccg.github.io/meetings/2021-05-06-vchttpapi/#resolution-1
