### ISSUE TITLE
verifyPresentation out of synch with the latest VerifyOptions

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/vc-http-api#206]
https://github.com/w3c-ccg/vc-http-api/blob/main/packages/vc-http-api-test-server/__tests__/verifyPresentation.spec.js
is still based on the `checks` model (from v0.0.0), should be updated to reflect the `VerifyOptions` model (from v0.0.2 and latest).

**Comment by OR13** [comment]
I think we need to document support for this:

for verifyProof:

```
"checks": ["proof", "credentialStatus"],
"domain": "example.com",
"challenge": "123"
```


Then add tests for:

"A revoked credential verifies successfully when "credentialStatus" is not in checks". or

"A credential with "credentialStatus" cannot be verified without requiring checks to include "credentialStatus".

Probably for the verify API we should be explicit as possible and not 'infer' the checks to run, from the payload by itself.

**Comment by nissimsan** [comment]
Yes, precisely. 

In particular it's this file: 
https://github.com/w3c-ccg/vc-http-api/blob/main/docs/components/VerifyOptions.yml
which has no mention of `checks`.

**Comment by nissimsan** [comment]
This looks good now: 
https://w3c-ccg.github.io/vc-http-api/verifier.html#operation/verifyPresentation
Seems this was just an interim state. Closing.
