### ISSUE TITLE
Agree to API Style Guide

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-http-api#35]
In order to address API Design preferences, I feel it's helpful to have a discussion, and then develop a style guide that codifies the choices we made as a group.

- https://restfulapi.net/resource-naming/
- https://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm

In my opinion, it's best to start with a base document, I propose we generally try to follow: 
- https://restfulapi.net

In cases where optionality is allowed, we should make a concrete decision, and state so in a markdown document... For example:

https://restfulapi.net/versioning/

> Using the URI is the most straightforward approach (and most commonly used as well) though it does violate the principle that a URI should refer to a unique resource. You are also guaranteed to break client integration when a version is updated.

We are specifically choosing not to use URI based versioing schemes for the reasons mentioned above ^

Per https://restfulapi.net/resource-naming/ 

It sounds like we are debating if the issue api is a `controller`, `document` or `collection`... its possible we could use all 3...

POST http://api.example.com/credential-management/credentials 
 => (collection: create credential)

PUT http://api.example.com/credential-management/credentials/{id} 
=> (document:  update credential)

POST http://api.example.com/credential-management/credentials/{id}/issue 
=> (controller: issue a verifiable credential from a credential)

POST http://api.example.com/credential-management/issuer/issue 
=> (controller: compose and issue a verifiable credential at the same time)

Lets look at an example:

Lets call a json object without a proof that will be used to issue a verifiable credential a "Credential"
Lets call a json object that has a proof a "Verifiable Credential"
Lets call a function that is called to issue a "Verifiable Credential" an "Issuer/Issue"
Lets call a function that is called to revoke a "Verifiable Credential" an "Issuer/Revoke"

Notice that POST `/issuer/revoke ` and PUT `/credential-management/credentials/{id}` are 2 potential ways of revoking... One is controller oriented, the other is resource oriented.

**Comment by msporny** [comment]
The group discussed this today and came to the following resolution:

RESOLVED: In general, the VC HTTP API style will conform to restfulapi.net guidelines and specifically use a 'controller' style for endpoints and will use JSON Schema to define the acceptable inputs to the APIs. Any deviation from these guidelines will be discussed in the group.

Marking as pending close.
