### ISSUE TITLE
Define Reference ID

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-http-api#36]
Is it the `vc.id` or a linked identifier for it?

**Comment by OR13** [comment]
believe this is now obsolete, templating no longer supported.

**Comment by msporny** [comment]
We made a decision on the 2021-07-20 telecon that resolved to not support templating or any other reference IDs, closing based on this resolution:  

RESOLVED: Regarding issue https://github.com/w3c-ccg/vc-http-api/issues/34, if a caller desires to build a VC incrementally of from a template, the caller can use another API to do so and then send the fully formed VC to the VC HTTP API for processing.
