### ISSUE TITLE
Capture requirements to support ZKP proof credentials

### ISSUE THREAD

**Issue by mavarley** [w3c-ccg/vc-http-api#38]
The current architecture and API assume that an Application layer process or Communication interface abstraction can successfully collect all the required information from a Holder and then construct an appropriate VC data model to then receive back a fully formed VC. 

This may be true for signature based formats (LD and JWS) but we need clarity on requirements for ZKP formats (or associated agents?); does the Issuer HTTP API need a communication path to the Holder to exchange additional cryto material for generating the ZKP signature? Or some other functionality?

@dhh1128 or other community members working with ZKP please provide insight on changes to the API required for this proof format.

Issue was identified in w3c-ccg/vc-issuer-http-api#27 and w3c-ccg/vc-issuer-http-api#16.

**Comment by msporny** [comment]
We discussed this on the 2021-07-20 telecon, @mavarley is going to talk with @dhh1128 to provide guidance on this issue... to ask specifically about CL Signature ZKPs.

**Comment by mavarley** [comment]
After getting some clarity from @dhh1128 and @swcurran on CL signature VCs, the conclusion was this issue (as is) is not the "right" issue to solve, and should instead maybe be broken out into a couple other issues to consider, for the following reasons:

1. ZKPs with BBS+ can already be supported by the API, and any new crypto technique (ZKP or not) would need to be vetted before inclusion ("ZKP" is just too broad a term).
2. VCs with CL signatures (as used in Aries) require a few pieces of Holder input; but other VC types (even schemas, not crypto related) may require the same function; where the Holder provides some of the input data to the VC. Currently this is all done 'out-of-band' form this API (like the subject DID collection and vetting). This is not specific to "ZKP".
3. The 'bad issuer' example @dhh1128 provides above, where a Holder requests one type of credential but instead receives another, is addressed in the Aries VC-CL sig model in a specific way - the VC-HTTP-API as it is today may be at risk of this vulnerability. This is not specific to "ZKP".

So the actions I would propose, and I believe @dhh1128 would support but he can chime in, (and the comments in brackets are definitely my own) would be as follows:

1. Close this issue, and any additional crypto signature scheme to be added to the API would require its own issue/PR,
2. If the community sees a need, open a new issue for "Holder input parameters" API support (personally I believe this to be out of scope at this time, but it may come up again).
3. If the community sees a need, open an issue to address the 'bad issuer' possibility (personally I believe this risk is something that gets addressed in a 'security considerations' section of the spec if required; but preventing 'bad issuers' in general can be quite a challenge and may be out of scope of this API).

Thoughts and feedback on the above?

**Comment by msporny** [comment]
> * ZKPs with BBS+ can already be supported by the API, and any new crypto technique (ZKP or not) would need to be vetted before inclusion ("ZKP" is just too broad a term).

Agreed.

> * VCs with CL signatures (as used in Aries) require a few pieces of Holder input; but other VC types (even schemas, not crypto related) may require the same function; where the Holder provides some of the input data to the VC. Currently this is all done 'out-of-band' form this API (like the subject DID collection and vetting). This is not specific to "ZKP".

Getting the information from the Holder is out of band. Providing that information to the API is in scope, IMO, but that sort of stuff tends to be proof-specific (and we have a way to pass in proof options today). I think we're covered here, but we'd need more examples of various proof types that need these sorts of options to be specified to be sure that we're covered. The only way we get there is by supporting multiple proof types (which I'm pretty sure the group intends to do).

> * The 'bad issuer' example @dhh1128 provides above, where a Holder requests one type of credential but instead receives another, is addressed in the Aries VC-CL sig model in a specific way - the VC-HTTP-API as it is today may be at risk of this vulnerability. This is not specific to "ZKP".

Hrm, need more detail here on the attack. I don't want to presume knowing the details of the attack.

> * Close this issue, and any additional crypto signature scheme to be added to the API would require its own issue/PR,

+1

> * If the community sees a need, open a new issue for "Holder input parameters" API support (personally I believe this to be out of scope at this time, but it may come up again).

I think we already support proof options (Holder input parameters are a subset of these)... so would need to understand if everyone's understanding is the same. If so, we're good. If not, we should raise an issue and discuss.

> * If the community sees a need, open an issue to address the 'bad issuer' possibility (personally I believe this risk is something that gets addressed in a 'security considerations' section of the spec if required; but preventing 'bad issuers' in general can be quite a challenge and may be out of scope of this API).

+1 to raise an issue and discuss this. At the very least, we need to talk about it in security considerations.

**Comment by msporny** [comment]
ACTION: @mavarley to open an issue related to "bad issuer" use case.

Otherwise discussion on 2021-07-27 resulted in the group agreeing with @mavarley's proposals https://github.com/w3c-ccg/vc-http-api/issues/38#issuecomment-884973768 and not objecting to close this issue.
