### ISSUE TITLE
Concern on external API for status checks

### ISSUE THREAD

**Issue by mavarley** [w3c-ccg/vc-http-api#39]
Entities (including Verifiers) may require a method of determining whether a Verifiable Credential or Presentation they are processing is still valid/active - one possibility is for the Issuer to provide a 'status check' endpoint.

There are concerns with this approach, in that it goes counter to the nature of the SSI design to have Verifiers "calling home" to Issuers whenever a Credential/Presentation is used.

Should this status-check functionality be part of this API?

@David-Chadwick @peacekeeper @dhh1128 this is a concern raised in w3c-ccg/vc-issuer-http-api#27 and w3c-ccg/vc-issuer-http-api#17

**Comment by mprorock** [comment]
there are valid reasons to have a status check - but i am concerned with anything other than allowing this as strictly optional if included at all for privacy concerns

**Comment by msporny** [comment]
The VC HTTP API Work Item group resolved the following on the 2021-07-27 call: 

RESOLVED: The VC HTTP API Work Item group will not define a "phone home" mechanism at present as it may create a privacy danger when a verifier contacts an issuer directly about a particular credential. Vendors are free to implement such a system, but we are not going to define it in the standard at present.

Closing.
