### ISSUE TITLE
Service APIs rather than RESTful APIs?

### ISSUE THREAD

**Issue by jchartrand** [w3c-ccg/vc-http-api#43]
Maybe REST isn't the right approach.

A RESTful GET might make sense for getting a credential (although as @dhh1128 points out in w3c-ccg/vc-issuer-http-api#12 possibly not), but maybe a POST for creating a credential isn’t the right level of abstraction?  

Since there is so much that goes on when creating a credential, and so much that could vary from one implementation to another (as @David-Chadwick points out in w3c-ccg/vc-issuer-http-api#9) then maybe trying to define a ‘service’ model might be more appropriate, where we’d (try to) define any standard functions that contribute to issuance (if there are any?) and that could be encapsulated within a service call or function invocation.  And ideally define those service as finely-grained as possible, to allow more flexibility in orchestrating different flows in different systems.  So people could mix and match bits and pieces in their respective systems, using functions/services whose implementations are abstracted away behind APIs.  

I guess I'm kind of thinking along the lines of NPM packages, pulling in whatever packages are needed for a given application, and wiring them up in javascript.  As an example, one package might do something like construct the JSON for the VCs given a list of holders.  But the package/module would follow an API and so could be replaced by another package as needed.

I don't know - is it even possible to decompose the bits and pieces of issuance into functions that are somewhat standard across systems?  The definition (API) of the functions themselves could be the json passed to a function as an argument, the json returned from the function, and any relevant side effects (like writing a transaction to a blockchain to get a timestamp).  I don’t know - is this even feasible, or are systems too complicated to work this way?

**Comment by OR13** [comment]
This should be closed, we agree to controller style API and https://restfulapi.net/resource-naming/
