### ISSUE TITLE
Why do we believe the issuer retains a copy of all issued credentials?

### ISSUE THREAD

**Issue by dhh1128** [w3c-ccg/vc-http-api#49]
The national government of most countries doesn't retain a copy of every passport they issue. Instead, they retain the data that went into the passport.

But in this API, we are assuming that when we GET /credential/{ref}, we get back the credential itself. I'm not sure that's a reasonable behavior, because it means a malicious sysadmin is guaranteed to be able to get not just the data for a credential, but the actual signatures that went on that credential, on demand.

**Comment by OR13** [comment]
We don't believe the issuer keeps a copy.

**Comment by msporny** [comment]
This was discussed on the 2021-08-03 call. The group feels like a broader discussion needs to occur wrt. what information an issuer needs to maintain in order to provide the endpoints it provides. At present, whether or not information is retained is not defined in the specification. We expect the group to have multiple conversations on this topic.

**Comment by msporny** [comment]
@dhh1128 please create a new, more accurate issue to track your concern. The group is concerned that the issue is vague as stated (since the API doesn't do this today) and because we'll need to have future conversations on the topic.

**Comment by dhh1128** [comment]
I am not able to participate in this group much right now, so assigning work to me is unlikely to produce action. :-)

I will close this issue at your request -- not because I feel the concern is resolved, but because my own commitment to the question is limited by my available attention. If anyone else in the group wants to pick up the topic and log more specific questions, they are free to do so. Otherwise, the work can proceed and time will eventually tell us whether there was any issue worth worrying about. :-)

**Comment by msporny** [comment]
> I am not able to participate in this group much right now, so assigning work to me is unlikely to produce action.

Acknowledged. Our work mode puts an emphasis on ensuring that we check back in with the person that raised an issue to enable them to have the final say on how to proceed. This question did raise a bit of discussion, but it went in a variety of directions (what about information needed for revocation lists, what if revocation lists are handled external to the issuer, don't issuers keep a complete record for audit purposes in some cases, etc... all of these are questions we will almost certainly pick up later) and the request from the group was to get to specific topics we can discuss.

So, while the answer to "Why do we believe the issuer retains a copy of all issued credentials?" was "We make no such assumption anywhere in the specification today, and are highly unlikely to make that assumption in the future.", the group felt like more discussion was necessary, but anchored to concrete decisions that needed to be made wrt. the APIs.
