### ISSUE TITLE
Support issuing LOTS of VCs 

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/vc-http-api#64]
Making sure we don't lose track of this. From @msporny 
https://github.com/transmute-industries/vc-http-api/issues/1#issue-659438260

**Comment by peacekeeper** [comment]
There seems to be a newer issuer where this is discussed: https://github.com/w3c-ccg/vc-http-api/issues/87.

I propose to close this one here.

**Comment by OR13** [comment]
agreed, closing
