### ISSUE TITLE
port Architecture doc from old repo?

### ISSUE THREAD

**Issue by mavarley** [w3c-ccg/vc-http-api#77]
I have noticed that the various versions of this API have not included the Architecture document:
https://github.com/w3c-ccg/vc-issuer-http-api/blob/master/architecture.md

I see value in having this doc included with the API spec to provide context on its intended usage and role in a broader deployment; fully recognizing that it may need to be updated for newer versions. The architecture doc was originally provided at the request of other community members asking "what is this for?"

If other owners see value in the doc let's figure out a way to bring it over (which directory) and then we can update it for newer versions. It can even be added to the README if it provides a nice overview context.

If other owners prefer this kind of information is captured elsewhere or in another format no problem, happy to help it find a new home.

**Comment by peacekeeper** [comment]
+1 to copying that over to this repo.

**Comment by OR13** [comment]
Let's move this over asap.

We may want to host it here:

https://github.com/w3c-ccg/vc-http-api/tree/master/docs

and link to it from the root readme at the top.

**Comment by bumblefudge** [comment]
closey closey?
