### ISSUE TITLE
Support for OAuth API protection for vendor API

### ISSUE THREAD

**Issue by tplooker** [w3c-ccg/vc-http-api#86]
Our (and I would assume other vendors) issuance and verification API's currently require OAuth bearer tokens for request authorization. Adding support to the test suite as an optional feature for vendors using this authorization strategy would prevent them from having to expose un-protected API's. A more advanced implementation might consider a client credentials flow implementation back to the authorization server to obtain the access token rather than it being supplied directly to the test runner. Happy to provide work on this feature if others are not opposed to its addition?

**Comment by OR13** [comment]
For example: https://petstore.swagger.io/ supports configuration with client credentials and https://github.com/swagger-api/swagger-ui/blob/master/dist/oauth2-redirect.html

I would love to see this supported.

**Comment by peacekeeper** [comment]
Good idea. In the initial design we decided to leave API authorization out of scope, but why not add it now :) As long as it's clear that this is an optional feature..

**Comment by OR13** [comment]
I propose we mark this feature as in scope for the version we will freeze in march.

**Comment by mprorock** [comment]
thumbs up from us on this.  oath will be pretty essential for us

**Comment by bumblefudge** [comment]
We love you

**Comment by OR13** [comment]
everyone is eagerly waiting a PR for this.
