### ISSUE TITLE
Add support for Revocation List 2020

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-http-api#90]
We need HTTP interface changes to support this.

We expect to need to see some examples to show how a credential which used this would be "issued" and "verified"

**Comment by OR13** [comment]
@tplooker to open a PR to demonstrate how they are handling this today.

**Comment by peacekeeper** [comment]
+1, ideally this would be done in a generic/extensible way that will also support future values of `credentialStatus`.

**Comment by peacekeeper** [comment]
I expect this would also impact https://github.com/w3c-ccg/vc-http-api/issues/62 and https://github.com/w3c-ccg/vc-http-api/issues/74 (the list of "checks" that are performed and returned by the Verifier API).

**Comment by bumblefudge** [comment]
sidenote: I have heard multiple projects in DIF discuss registering future values of `credentialStatus`  ["someday"], so the dream of multiple revocation methods available to LD systems *is* alive, at least conversationally.  hopefully in time for the march 2022 plugathon :)

**Comment by OR13** [comment]
There is some risk of a pseudo-hostile fork to the revocation list spec by Microsoft noted here: https://github.com/w3c-ccg/vc-status-rl-2020/issues/6#issuecomment-769970219

If they can't use this work for statuses other than revoked, they are likely to embrace, extend and extinguish :)
