### ISSUE TITLE
improve user experience around developer docs

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/vc-http-api#96]
currently the base swagger libraries are used to generate the developer docs around the APIs.  cleaner interfaces exist that also allow for responsiveness, and cleaner layout for payloads and responses, and can serve as a baseline to adding better documentation on the project.

some screenshot examples of alternatives are attached with both desktop and mobile views

![Screenshot from 2021-02-03 13-33-09](https://user-images.githubusercontent.com/3495140/106792738-8c156400-6624-11eb-80af-8f69512f254d.png)
![Screenshot from 2021-02-03 13-33-52](https://user-images.githubusercontent.com/3495140/106792751-8fa8eb00-6624-11eb-8f71-3b5f8684c0f3.png)

**Comment by OR13** [comment]
this looks great, lets ask the question about nice URLs...

https://github.com/w3c-ccg/vc-http-api - > redoc
https://github.com/w3c-ccg/vc-http-api/swagger -> swagger 

https://w3c-ccg.github.io/vc-http-api/versions/v0.0.0/ ->  redoc
https://w3c-ccg.github.io/vc-http-api/versions/v0.0.0/swagger/ ->  swagger


Or should it be the other way around?

**Comment by mprorock** [comment]
we have had good luck linking into both from the docs so that the developer has a choice.  then the community/top level on the project can decide what the default for the index is. pr #99

**Comment by mprorock** [comment]
editors: @peacekeeper @msporny @mavarley @OR13 @mkhraisha 
can we add the tag: `plugfest-march-2021` to this issue

**Comment by mkhraisha** [comment]
I believe this can be closed as these routes are now accessible from https://w3c-ccg.github.io/vc-http-api/issuer for example.

**Comment by msporny** [comment]
Marking `pending close` -- this will be closed in 7 days unless there are objections.
